### ISSUE TITLE
Fix the UI for smaller widths (when table is shown)

### ISSUE THREAD

**Issue by virajvchavan** [virajvchavan/github-leaderboards-ui#5]
@Neelam618

**Comment by kritika902** [comment]
plzz assign this to me sir i can fix it

**Comment by kritika902** [comment]
Thanku sir

**Comment by Inncoent2003** [comment]
but it does not have a lable of hacktoberfest

**Comment by Inncoent2003** [comment]
will complete under 2 days

**Comment by kritika902** [comment]
sir u can check the changes related to this project and let me know about others changes if needed
